version: 2

multi-ecosystem-groups:
  dependencies:
    schedule:
      interval: "monthly"
    labels:
      - "dependency"

updates:
  - package-ecosystem: "pip"
    directory: "/" # Location of package manifests
    ecosystem: "dependencies"
  - package-ecosystem: "github-actions"
    directory: "/"
    ecosystem: "dependencies"
