version: 2

multi-ecosystem-groups:
  dependencies:
    schedule:
      interval: "monthly"
    labels:
      - "dependency"

updates:
  - package-ecosystem: "pip"
    directory: "/" # Location of package manifests
    patterns: ["*"]
    multi-ecosystem-group: "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "dependencies"
