version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    labels:
      - "dependency"
    reviewers:
      - "danielnoord"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependency"
    reviewers:
      - "danielnoord"
