repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
        exclude: "tests/data/format/whitespace_stripper|tests/data/format/quotes_type|tests/test_config.py"
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
        exclude: &test-data "tests/data"
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        exclude: *test-data
        args:
          - --in-place
          - --remove-all-unused-imports
          - --expand-star-imports
          - --remove-duplicate-keys
          - --remove-unused-variables
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.32.1
    hooks:
      - id: pyupgrade
        args: [--py38-plus]
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        exclude: *test-data
        args: [--quiet]
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        exclude: *test-data
        additional_dependencies: [flake8-typing-imports==1.10.1]
  - repo: https://github.com/pycqa/pylint
    rev: v2.14.0-b1
    hooks:
      - id: pylint
        exclude: *test-data
        args: ["--disable=import-error, cyclic-import"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.950
    hooks:
      - id: mypy
        args: [--config-file=pyproject.toml]
        exclude: *test-data
        additional_dependencies:
          [pytest-stub==1.1.0, types-docutils~=0.17.5, sphinx~=4.4]
  - repo: https://github.com/DanielNoord/pydocstringformatter
    rev: v0.6.0
    hooks:
      - id: pydocstringformatter
        exclude: *test-data
        args: []
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
      - id: prettier
        exclude: *test-data
        args: [--prose-wrap=always, --print-width=88]
